# -*- coding: utf-8 -*-
"""Día1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9ClRUdeQ6Sp5IH4pU5EQOxVQZl0dRdV

Input y Output
"""

print("Hola mundo")
print(6+6)
print("6+6")

print("¿Cómo te llamas?") #Se imprime pregunta
##IMPORTANTE: todo input es string
var1 = input("Escribe aquí tu nombre: ") # Input
print("¡Hola " + var1 + "!") #Output

"""Definición de variables"""

variable1 = 7 #SE define como un entero
variable2 = int(variable1) #int : enteros
variable3 = "string" #string: cadena de caracteres
variable4 = float(2.3)  #float es decimal
##IMPORTATE: El nombre de una variable no tiene espacios, ni inicia con mayúsculas
## nombre_de_variable_grande_valido =
## nombre no valido =

"""Simbolos y operaciones básicas"""

print("Suma: ", 2+3)
print("Resta: ", 7-5)
print("multiplicacion: ", 4*6)
print("potencia: ", 2**3)
print("division: ", 9/3)
print("division entera: ", 7//2)
print("modulo", 7%2)

"""Más simbolos (Booleanos)"""

print("igual que: ", 7==5)  #false
print("menorque: ", 3<8) #true
print("mayorque: ",7>5) #true
print("distinto que: ", 9!=1 )#true
print("menorigual: ", 5<=5) #true
print("mayorigual: ", 5>=8) #false

"""Ejemplo de Condicional

"""

#Ejemplo de condicional en Python

# Variables de ejemplo
x = 10
y = 5

# Ejemplo de condicional
if x > y:
    print("x es mayor que y")
else:
    print("x no es mayor que y")

#Otro ejemplo
if x > 5:
    print("El valor de x es mayor que 5")
elif x == 5:
    print("El valor de x es igual a 5")
else:
    print("El valor de x es menor que 5")